from dataclasses import dataclass


@dataclass(frozen=True)
class Product:
    sku: str
    category: str
    product_name: str
    color: str
    size: str
    season: str
    material: str
    price_zar: float
    stock_quantity: int
    available_colors: tuple[str, ...] = ()
    available_sizes: tuple[str, ...] = ()
    source: str = "workbook"


INVENTORY = [
    Product(
        sku='SKU-1001',
        category='Skirts',
        product_name='Red A-Line Skirt',
        color='Red',
        size='M',
        season='Spring',
        material='Polyester Blend',
        price_zar=710.99,
        stock_quantity=24,
    ),
    Product(
        sku='SKU-1002',
        category='Jeans',
        product_name='Navy Straight Leg Jeans',
        color='Navy',
        size='XS',
        season='All Season',
        material='Denim (Cotton/Elastane)',
        price_zar=970.99,
        stock_quantity=10,
    ),
    Product(
        sku='SKU-1003',
        category='Activewear',
        product_name='Mustard Sports Bra',
        color='Mustard',
        size='XS',
        season='All Season',
        material='Polyester/Spandex',
        price_zar=470.99,
        stock_quantity=58,
    ),
    Product(
        sku='SKU-1004',
        category='Socks',
        product_name='Forest Green Crew Socks',
        color='Forest Green',
        size='S',
        season='All Season',
        material='Cotton/Polyester Blend',
        price_zar=110.99,
        stock_quantity=26,
    ),
    Product(
        sku='SKU-1005',
        category='Sweaters',
        product_name='Sky Blue Cable Knit Sweater',
        color='Sky Blue',
        size='XS',
        season='Winter',
        material='Wool Blend',
        price_zar=840.99,
        stock_quantity=93,
    ),
    Product(
        sku='SKU-1006',
        category='Outerwear Accessories',
        product_name='Mustard Scarf',
        color='Mustard',
        size='S',
        season='Autumn',
        material='Acrylic Knit',
        price_zar=240.99,
        stock_quantity=34,
    ),
    Product(
        sku='SKU-1007',
        category='Sweaters',
        product_name='Red Knit Sweater',
        color='Red',
        size='S',
        season='Autumn',
        material='Wool Blend',
        price_zar=1030.99,
        stock_quantity=98,
    ),
    Product(
        sku='SKU-1008',
        category='Socks',
        product_name='White Wool Socks',
        color='White',
        size='S',
        season='All Season',
        material='Cotton/Polyester Blend',
        price_zar=110.99,
        stock_quantity=51,
    ),
    Product(
        sku='SKU-1009',
        category='Shorts',
        product_name='Sky Blue Linen Shorts',
        color='Sky Blue',
        size='XS',
        season='Summer',
        material='Cotton Twill',
        price_zar=540.99,
        stock_quantity=120,
    ),
    Product(
        sku='SKU-1010',
        category='T-Shirts',
        product_name='Cream Muscle Tee',
        color='Cream',
        size='S',
        season='Spring',
        material='100% Cotton',
        price_zar=270.99,
        stock_quantity=113,
    ),
    Product(
        sku='SKU-1011',
        category='Jackets',
        product_name='Pink Puffer Jacket',
        color='Pink',
        size='S',
        season='Autumn',
        material='Polyester/Nylon Blend',
        price_zar=1150.99,
        stock_quantity=31,
    ),
    Product(
        sku='SKU-1012',
        category='Jeans',
        product_name='Red Skinny Jeans',
        color='Red',
        size='XL',
        season='All Season',
        material='Denim (Cotton/Elastane)',
        price_zar=1140.99,
        stock_quantity=114,
    ),
    Product(
        sku='SKU-1013',
        category='Socks',
        product_name='Rust Ankle Socks',
        color='Rust',
        size='M',
        season='All Season',
        material='Cotton/Polyester Blend',
        price_zar=80.99,
        stock_quantity=65,
    ),
    Product(
        sku='SKU-1014',
        category='Outerwear Accessories',
        product_name='Denim Blue Gloves',
        color='Denim Blue',
        size='XS',
        season='Winter',
        material='Acrylic Knit',
        price_zar=390.99,
        stock_quantity=14,
    ),
    Product(
        sku='SKU-1015',
        category='Socks',
        product_name='Beige Compression Socks',
        color='Beige',
        size='S',
        season='All Season',
        material='Cotton/Polyester Blend',
        price_zar=70.99,
        stock_quantity=49,
    ),
    Product(
        sku='SKU-1016',
        category='Hoodies',
        product_name='Rust Pullover Hoodie',
        color='Rust',
        size='XL',
        season='Autumn',
        material='Cotton Fleece',
        price_zar=780.99,
        stock_quantity=32,
    ),
    Product(
        sku='SKU-1017',
        category='Jeans',
        product_name='Red Slim Fit Jeans',
        color='Red',
        size='XS',
        season='All Season',
        material='Denim (Cotton/Elastane)',
        price_zar=1280.99,
        stock_quantity=96,
    ),
    Product(
        sku='SKU-1018',
        category='Activewear',
        product_name='Sky Blue Track Pants',
        color='Sky Blue',
        size='M',
        season='All Season',
        material='Polyester/Spandex',
        price_zar=480.99,
        stock_quantity=55,
    ),
    Product(
        sku='SKU-1019',
        category='Hoodies',
        product_name='Olive Cropped Hoodie',
        color='Olive',
        size='L',
        season='Winter',
        material='Cotton Fleece',
        price_zar=910.99,
        stock_quantity=112,
    ),
    Product(
        sku='SKU-1020',
        category='Swimwear',
        product_name='Sky Blue Bikini Set',
        color='Sky Blue',
        size='XL',
        season='Summer',
        material='Nylon/Spandex',
        price_zar=670.99,
        stock_quantity=116,
    ),
    Product(
        sku='SKU-1021',
        category='Jackets',
        product_name='Grey Denim Jacket',
        color='Grey',
        size='M',
        season='Spring',
        material='Polyester/Nylon Blend',
        price_zar=2090.99,
        stock_quantity=77,
    ),
    Product(
        sku='SKU-1022',
        category='Dresses',
        product_name='Burgundy Wrap Dress',
        color='Burgundy',
        size='S',
        season='Spring',
        material='Viscose Blend',
        price_zar=650.99,
        stock_quantity=69,
    ),
    Product(
        sku='SKU-1023',
        category='Jeans',
        product_name='Camel Mom Jeans',
        color='Camel',
        size='XS',
        season='All Season',
        material='Denim (Cotton/Elastane)',
        price_zar=1220.99,
        stock_quantity=2,
    ),
    Product(
        sku='SKU-1024',
        category='Skirts',
        product_name='Grey Denim Skirt',
        color='Grey',
        size='M',
        season='Spring',
        material='Polyester Blend',
        price_zar=500.99,
        stock_quantity=7,
    ),
    Product(
        sku='SKU-1025',
        category='Jeans',
        product_name='Mustard Wide Leg Jeans',
        color='Mustard',
        size='XL',
        season='All Season',
        material='Denim (Cotton/Elastane)',
        price_zar=700.99,
        stock_quantity=93,
    ),
    Product(
        sku='SKU-1026',
        category='Hoodies',
        product_name='Denim Blue Fleece Hoodie',
        color='Denim Blue',
        size='XS',
        season='Winter',
        material='Cotton Fleece',
        price_zar=530.99,
        stock_quantity=84,
    ),
    Product(
        sku='SKU-1027',
        category='Shorts',
        product_name='Denim Blue Denim Shorts',
        color='Denim Blue',
        size='XL',
        season='Summer',
        material='Cotton Twill',
        price_zar=330.99,
        stock_quantity=67,
    ),
    Product(
        sku='SKU-1028',
        category='Activewear',
        product_name='Lavender Zip Track Jacket',
        color='Lavender',
        size='S',
        season='All Season',
        material='Polyester/Spandex',
        price_zar=490.99,
        stock_quantity=51,
    ),
    Product(
        sku='SKU-1029',
        category='Sweaters',
        product_name='Forest Green Turtleneck Sweater',
        color='Forest Green',
        size='L',
        season='Autumn',
        material='Wool Blend',
        price_zar=570.99,
        stock_quantity=31,
    ),
    Product(
        sku='SKU-1030',
        category='Dresses',
        product_name='Mustard Maxi Dress',
        color='Mustard',
        size='XS',
        season='Spring',
        material='Viscose Blend',
        price_zar=470.99,
        stock_quantity=75,
    ),
    Product(
        sku='SKU-1031',
        category='Swimwear',
        product_name='Red Board Shorts',
        color='Red',
        size='S',
        season='Summer',
        material='Nylon/Spandex',
        price_zar=350.99,
        stock_quantity=9,
    ),
    Product(
        sku='SKU-1032',
        category='Shorts',
        product_name='White Cargo Shorts',
        color='White',
        size='S',
        season='Summer',
        material='Cotton Twill',
        price_zar=530.99,
        stock_quantity=4,
    ),
    Product(
        sku='SKU-1033',
        category='Jackets',
        product_name='Cream Windbreaker',
        color='Cream',
        size='XS',
        season='Spring',
        material='Polyester/Nylon Blend',
        price_zar=1400.99,
        stock_quantity=35,
    ),
    Product(
        sku='SKU-1034',
        category='Dresses',
        product_name='Denim Blue Sweater Dress',
        color='Denim Blue',
        size='S',
        season='Summer',
        material='Viscose Blend',
        price_zar=1180.99,
        stock_quantity=73,
    ),
    Product(
        sku='SKU-1035',
        category='Socks',
        product_name='Denim Blue No-Show Socks',
        color='Denim Blue',
        size='S',
        season='All Season',
        material='Cotton/Polyester Blend',
        price_zar=120.99,
        stock_quantity=24,
    ),
    Product(
        sku='SKU-1036',
        category='Outerwear Accessories',
        product_name='Grey Sun Hat',
        color='Grey',
        size='XS',
        season='Autumn',
        material='Acrylic Knit',
        price_zar=230.99,
        stock_quantity=54,
    ),
    Product(
        sku='SKU-1037',
        category='Jackets',
        product_name='Lavender Bomber Jacket',
        color='Lavender',
        size='L',
        season='Spring',
        material='Polyester/Nylon Blend',
        price_zar=930.99,
        stock_quantity=86,
    ),
    Product(
        sku='SKU-1038',
        category='Skirts',
        product_name='Grey Midi Skirt',
        color='Grey',
        size='XS',
        season='Spring',
        material='Polyester Blend',
        price_zar=560.99,
        stock_quantity=102,
    ),
    Product(
        sku='SKU-1039',
        category='Swimwear',
        product_name='Grey One-Piece Swimsuit',
        color='Grey',
        size='S',
        season='Summer',
        material='Nylon/Spandex',
        price_zar=470.99,
        stock_quantity=68,
    ),
    Product(
        sku='SKU-1040',
        category='Hoodies',
        product_name='Pink Oversized Hoodie',
        color='Pink',
        size='S',
        season='Autumn',
        material='Cotton Fleece',
        price_zar=560.99,
        stock_quantity=35,
    ),
    Product(
        sku='SKU-1041',
        category='Shorts',
        product_name='Pink Athletic Shorts',
        color='Pink',
        size='S',
        season='Summer',
        material='Cotton Twill',
        price_zar=390.99,
        stock_quantity=103,
    ),
    Product(
        sku='SKU-1042',
        category='Dresses',
        product_name='Red Slip Dress',
        color='Red',
        size='XS',
        season='Summer',
        material='Viscose Blend',
        price_zar=1140.99,
        stock_quantity=107,
    ),
    Product(
        sku='SKU-1043',
        category='T-Shirts',
        product_name='Black Basic Crew Tee',
        color='Black',
        size='XS',
        season='Summer',
        material='100% Cotton',
        price_zar=200.99,
        stock_quantity=52,
    ),
    Product(
        sku='SKU-1044',
        category='Dresses',
        product_name='Denim Blue Sundress',
        color='Denim Blue',
        size='L',
        season='Summer',
        material='Viscose Blend',
        price_zar=960.99,
        stock_quantity=115,
    ),
    Product(
        sku='SKU-1045',
        category='Activewear',
        product_name='White Leggings',
        color='White',
        size='S',
        season='All Season',
        material='Polyester/Spandex',
        price_zar=300.99,
        stock_quantity=49,
    ),
    Product(
        sku='SKU-1046',
        category='T-Shirts',
        product_name='Sky Blue Graphic Tee',
        color='Sky Blue',
        size='L',
        season='Spring',
        material='100% Cotton',
        price_zar=280.99,
        stock_quantity=89,
    ),
    Product(
        sku='SKU-1047',
        category='T-Shirts',
        product_name='Red Long Sleeve Tee',
        color='Red',
        size='L',
        season='Summer',
        material='100% Cotton',
        price_zar=210.99,
        stock_quantity=37,
    ),
    Product(
        sku='SKU-1048',
        category='Jackets',
        product_name='Burgundy Rain Jacket',
        color='Burgundy',
        size='XS',
        season='Spring',
        material='Polyester/Nylon Blend',
        price_zar=2180.99,
        stock_quantity=7,
    ),
    Product(
        sku='SKU-1049',
        category='Jackets',
        product_name='Cream Wool Coat',
        color='Cream',
        size='XS',
        season='Winter',
        material='Polyester/Nylon Blend',
        price_zar=2020.99,
        stock_quantity=64,
    ),
    Product(
        sku='SKU-1050',
        category='Sweaters',
        product_name='Camel Cardigan',
        color='Camel',
        size='S',
        season='Winter',
        material='Wool Blend',
        price_zar=820.99,
        stock_quantity=10,
    ),
    Product(
        sku='SKU-1051',
        category='Outerwear Accessories',
        product_name='Olive Beanie',
        color='Olive',
        size='XS',
        season='Winter',
        material='Acrylic Knit',
        price_zar=330.99,
        stock_quantity=110,
    ),
    Product(
        sku='SKU-1052',
        category='Hoodies',
        product_name='Mustard Zip-Up Hoodie',
        color='Mustard',
        size='L',
        season='Winter',
        material='Cotton Fleece',
        price_zar=810.99,
        stock_quantity=31,
    ),
    Product(
        sku='SKU-1053',
        category='T-Shirts',
        product_name='White V-Neck Tee',
        color='White',
        size='XL',
        season='Summer',
        material='100% Cotton',
        price_zar=280.99,
        stock_quantity=84,
    ),
    Product(
        sku='SKU-1054',
        category='Skirts',
        product_name='Camel Pleated Skirt',
        color='Camel',
        size='M',
        season='Spring',
        material='Polyester Blend',
        price_zar=480.99,
        stock_quantity=85,
    ),
    Product(
        sku='SKU-1055',
        category='Skirts',
        product_name='Cream A-Line Skirt',
        color='Cream',
        size='S',
        season='Spring',
        material='Polyester Blend',
        price_zar=600.99,
        stock_quantity=16,
    ),
    Product(
        sku='SKU-1056',
        category='Jeans',
        product_name='Charcoal Straight Leg Jeans',
        color='Charcoal',
        size='L',
        season='All Season',
        material='Denim (Cotton/Elastane)',
        price_zar=690.99,
        stock_quantity=1,
    ),
    Product(
        sku='SKU-1057',
        category='Activewear',
        product_name='Pink Sports Bra',
        color='Pink',
        size='XL',
        season='All Season',
        material='Polyester/Spandex',
        price_zar=340.99,
        stock_quantity=68,
    ),
    Product(
        sku='SKU-1058',
        category='Socks',
        product_name='Burgundy Crew Socks',
        color='Burgundy',
        size='XL',
        season='All Season',
        material='Cotton/Polyester Blend',
        price_zar=80.99,
        stock_quantity=119,
    ),
    Product(
        sku='SKU-1059',
        category='Sweaters',
        product_name='Forest Green Cable Knit Sweater',
        color='Forest Green',
        size='XS',
        season='Winter',
        material='Wool Blend',
        price_zar=730.99,
        stock_quantity=36,
    ),
    Product(
        sku='SKU-1060',
        category='Outerwear Accessories',
        product_name='Olive Scarf',
        color='Olive',
        size='L',
        season='Autumn',
        material='Acrylic Knit',
        price_zar=310.99,
        stock_quantity=103,
    ),
    Product(
        sku='SKU-1061',
        category='Sweaters',
        product_name='Camel Knit Sweater',
        color='Camel',
        size='XS',
        season='Autumn',
        material='Wool Blend',
        price_zar=1090.99,
        stock_quantity=84,
    ),
    Product(
        sku='SKU-1062',
        category='Socks',
        product_name='Grey Wool Socks',
        color='Grey',
        size='S',
        season='All Season',
        material='Cotton/Polyester Blend',
        price_zar=70.99,
        stock_quantity=113,
    ),
    Product(
        sku='SKU-1063',
        category='Shorts',
        product_name='Grey Linen Shorts',
        color='Grey',
        size='XL',
        season='Summer',
        material='Cotton Twill',
        price_zar=330.99,
        stock_quantity=36,
    ),
    Product(
        sku='SKU-1064',
        category='T-Shirts',
        product_name='Burgundy Muscle Tee',
        color='Burgundy',
        size='M',
        season='Summer',
        material='100% Cotton',
        price_zar=230.99,
        stock_quantity=64,
    ),
    Product(
        sku='SKU-1065',
        category='Jackets',
        product_name='Denim Blue Puffer Jacket',
        color='Denim Blue',
        size='M',
        season='Winter',
        material='Polyester/Nylon Blend',
        price_zar=1030.99,
        stock_quantity=81,
    ),
    Product(
        sku='SKU-1066',
        category='Jeans',
        product_name='Lavender Skinny Jeans',
        color='Lavender',
        size='M',
        season='All Season',
        material='Denim (Cotton/Elastane)',
        price_zar=600.99,
        stock_quantity=42,
    ),
    Product(
        sku='SKU-1067',
        category='Socks',
        product_name='Beige Ankle Socks',
        color='Beige',
        size='M',
        season='All Season',
        material='Cotton/Polyester Blend',
        price_zar=130.99,
        stock_quantity=70,
    ),
    Product(
        sku='SKU-1068',
        category='Outerwear Accessories',
        product_name='Lavender Gloves',
        color='Lavender',
        size='XL',
        season='Winter',
        material='Acrylic Knit',
        price_zar=150.99,
        stock_quantity=9,
    ),
    Product(
        sku='SKU-1069',
        category='Socks',
        product_name='Beige Compression Socks',
        color='Beige',
        size='XL',
        season='All Season',
        material='Cotton/Polyester Blend',
        price_zar=110.99,
        stock_quantity=74,
    ),
    Product(
        sku='SKU-1070',
        category='Hoodies',
        product_name='Red Pullover Hoodie',
        color='Red',
        size='S',
        season='Autumn',
        material='Cotton Fleece',
        price_zar=530.99,
        stock_quantity=5,
    ),
    Product(
        sku='SKU-1071',
        category='Jeans',
        product_name='Charcoal Slim Fit Jeans',
        color='Charcoal',
        size='M',
        season='All Season',
        material='Denim (Cotton/Elastane)',
        price_zar=1050.99,
        stock_quantity=26,
    ),
    Product(
        sku='SKU-1072',
        category='Activewear',
        product_name='Mustard Track Pants',
        color='Mustard',
        size='XS',
        season='All Season',
        material='Polyester/Spandex',
        price_zar=650.99,
        stock_quantity=113,
    ),
    Product(
        sku='SKU-1073',
        category='Hoodies',
        product_name='Lavender Cropped Hoodie',
        color='Lavender',
        size='XL',
        season='Winter',
        material='Cotton Fleece',
        price_zar=600.99,
        stock_quantity=110,
    ),
    Product(
        sku='SKU-1074',
        category='Swimwear',
        product_name='Olive Bikini Set',
        color='Olive',
        size='S',
        season='Summer',
        material='Nylon/Spandex',
        price_zar=360.99,
        stock_quantity=22,
    ),
    Product(
        sku='SKU-1075',
        category='Jackets',
        product_name='Cream Denim Jacket',
        color='Cream',
        size='L',
        season='Spring',
        material='Polyester/Nylon Blend',
        price_zar=1430.99,
        stock_quantity=34,
    ),
    Product(
        sku='SKU-1076',
        category='Dresses',
        product_name='Olive Wrap Dress',
        color='Olive',
        size='XS',
        season='Spring',
        material='Viscose Blend',
        price_zar=490.99,
        stock_quantity=109,
    ),
    Product(
        sku='SKU-1077',
        category='Jeans',
        product_name='Denim Blue Mom Jeans',
        color='Denim Blue',
        size='S',
        season='All Season',
        material='Denim (Cotton/Elastane)',
        price_zar=1180.99,
        stock_quantity=44,
    ),
    Product(
        sku='SKU-1078',
        category='Skirts',
        product_name='Charcoal Denim Skirt',
        color='Charcoal',
        size='S',
        season='Summer',
        material='Polyester Blend',
        price_zar=360.99,
        stock_quantity=84,
    ),
    Product(
        sku='SKU-1079',
        category='Jeans',
        product_name='Burgundy Wide Leg Jeans',
        color='Burgundy',
        size='L',
        season='All Season',
        material='Denim (Cotton/Elastane)',
        price_zar=950.99,
        stock_quantity=110,
    ),
    Product(
        sku='SKU-1080',
        category='Hoodies',
        product_name='Navy Fleece Hoodie',
        color='Navy',
        size='M',
        season='Autumn',
        material='Cotton Fleece',
        price_zar=860.99,
        stock_quantity=65,
    ),
    Product(
        sku='SKU-1081',
        category='Shorts',
        product_name='Rust Denim Shorts',
        color='Rust',
        size='XL',
        season='Spring',
        material='Cotton Twill',
        price_zar=250.99,
        stock_quantity=14,
    ),
    Product(
        sku='SKU-1082',
        category='Activewear',
        product_name='Sky Blue Zip Track Jacket',
        color='Sky Blue',
        size='S',
        season='All Season',
        material='Polyester/Spandex',
        price_zar=320.99,
        stock_quantity=13,
    ),
    Product(
        sku='SKU-1083',
        category='Sweaters',
        product_name='Lavender Turtleneck Sweater',
        color='Lavender',
        size='M',
        season='Autumn',
        material='Wool Blend',
        price_zar=770.99,
        stock_quantity=77,
    ),
    Product(
        sku='SKU-1084',
        category='Dresses',
        product_name='Camel Maxi Dress',
        color='Camel',
        size='XS',
        season='Spring',
        material='Viscose Blend',
        price_zar=1180.99,
        stock_quantity=24,
    ),
    Product(
        sku='SKU-1085',
        category='Swimwear',
        product_name='Sky Blue Board Shorts',
        color='Sky Blue',
        size='XS',
        season='Summer',
        material='Nylon/Spandex',
        price_zar=350.99,
        stock_quantity=66,
    ),
    Product(
        sku='SKU-1086',
        category='Shorts',
        product_name='Red Cargo Shorts',
        color='Red',
        size='S',
        season='Spring',
        material='Cotton Twill',
        price_zar=380.99,
        stock_quantity=8,
    ),
    Product(
        sku='SKU-1087',
        category='Jackets',
        product_name='Cream Windbreaker',
        color='Cream',
        size='XL',
        season='Autumn',
        material='Polyester/Nylon Blend',
        price_zar=1110.99,
        stock_quantity=92,
    ),
    Product(
        sku='SKU-1088',
        category='Dresses',
        product_name='Charcoal Sweater Dress',
        color='Charcoal',
        size='XL',
        season='Spring',
        material='Viscose Blend',
        price_zar=970.99,
        stock_quantity=41,
    ),
    Product(
        sku='SKU-1089',
        category='Socks',
        product_name='Rust No-Show Socks',
        color='Rust',
        size='M',
        season='All Season',
        material='Cotton/Polyester Blend',
        price_zar=90.99,
        stock_quantity=53,
    ),
    Product(
        sku='SKU-1090',
        category='Outerwear Accessories',
        product_name='Rust Sun Hat',
        color='Rust',
        size='S',
        season='Autumn',
        material='Acrylic Knit',
        price_zar=240.99,
        stock_quantity=70,
    ),
    Product(
        sku='SKU-1091',
        category='Jackets',
        product_name='Black Bomber Jacket',
        color='Black',
        size='M',
        season='Autumn',
        material='Polyester/Nylon Blend',
        price_zar=1330.99,
        stock_quantity=55,
    ),
    Product(
        sku='SKU-1092',
        category='Skirts',
        product_name='Cream Midi Skirt',
        color='Cream',
        size='L',
        season='Spring',
        material='Polyester Blend',
        price_zar=630.99,
        stock_quantity=86,
    ),
    Product(
        sku='SKU-1093',
        category='Swimwear',
        product_name='Burgundy One-Piece Swimsuit',
        color='Burgundy',
        size='XL',
        season='Summer',
        material='Nylon/Spandex',
        price_zar=820.99,
        stock_quantity=21,
    ),
    Product(
        sku='SKU-1094',
        category='Hoodies',
        product_name='Navy Oversized Hoodie',
        color='Navy',
        size='M',
        season='Autumn',
        material='Cotton Fleece',
        price_zar=500.99,
        stock_quantity=104,
    ),
    Product(
        sku='SKU-1095',
        category='Shorts',
        product_name='Mustard Athletic Shorts',
        color='Mustard',
        size='M',
        season='Summer',
        material='Cotton Twill',
        price_zar=500.99,
        stock_quantity=25,
    ),
    Product(
        sku='SKU-1096',
        category='Dresses',
        product_name='Beige Slip Dress',
        color='Beige',
        size='XS',
        season='Summer',
        material='Viscose Blend',
        price_zar=760.99,
        stock_quantity=60,
    ),
    Product(
        sku='SKU-1097',
        category='T-Shirts',
        product_name='Navy Basic Crew Tee',
        color='Navy',
        size='L',
        season='Spring',
        material='100% Cotton',
        price_zar=330.99,
        stock_quantity=24,
    ),
    Product(
        sku='SKU-1098',
        category='Dresses',
        product_name='Rust Sundress',
        color='Rust',
        size='L',
        season='Spring',
        material='Viscose Blend',
        price_zar=760.99,
        stock_quantity=18,
    ),
    Product(
        sku='SKU-1099',
        category='Activewear',
        product_name='Black Leggings',
        color='Black',
        size='L',
        season='All Season',
        material='Polyester/Spandex',
        price_zar=440.99,
        stock_quantity=22,
    ),
    Product(
        sku='SKU-1100',
        category='T-Shirts',
        product_name='Camel Graphic Tee',
        color='Camel',
        size='L',
        season='Summer',
        material='100% Cotton',
        price_zar=320.99,
        stock_quantity=31,
    ),
    Product(
        sku='STORE-TSHIRT',
        category='T-Shirts',
        product_name='Tshirt',
        color='',
        size='',
        season='All Season',
        material='Not specified',
        price_zar=500.0,
        stock_quantity=40,
        available_colors=('White',),
        available_sizes=('S', 'M', 'L', 'XL', 'XXL'),
        source='storeInventory',
    ),
    Product(
        sku='STORE-PANTS',
        category='Pants',
        product_name='Pants',
        color='',
        size='',
        season='All Season',
        material='Not specified',
        price_zar=450.0,
        stock_quantity=0,
        available_colors=('Black', 'Navy', 'Grey', 'Khaki'),
        available_sizes=('S', 'M', 'L', 'XL', 'XXL'),
        source='storeInventory',
    ),
    Product(
        sku='STORE-JACKET',
        category='Jackets',
        product_name='Jacket',
        color='',
        size='',
        season='All Season',
        material='Not specified',
        price_zar=650.0,
        stock_quantity=10,
        available_colors=('Black',),
        available_sizes=('S', 'M', 'L', 'XL', 'XXL'),
        source='storeInventory',
    ),
    Product(
        sku='STORE-BEANIES',
        category='Headwear',
        product_name='Beanies',
        color='',
        size='',
        season='All Season',
        material='Not specified',
        price_zar=150.0,
        stock_quantity=20,
        available_colors=('White', 'Grey', 'Blue', 'Red',
                          'Black', 'Pink', 'Yellow', 'Green'),
        available_sizes=(),
        source='storeInventory',
    ),
    Product(
        sku='STORE-SWEATER',
        category='Sweaters',
        product_name='Sweater',
        color='',
        size='',
        season='All Season',
        material='Not specified',
        price_zar=650.0,
        stock_quantity=15,
        available_colors=('Black',),
        available_sizes=('S', 'M', 'L', 'XL', 'XXL'),
        source='storeInventory',
    ),
    Product(
        sku='STORE-CARDIGAN',
        category='Sweaters',
        product_name='Cardigan',
        color='',
        size='',
        season='All Season',
        material='Not specified',
        price_zar=1200.0,
        stock_quantity=10,
        available_colors=('Black', 'White', 'Red'),
        available_sizes=('S', 'M', 'L', 'XL', 'XXL'),
        source='storeInventory',
    ),
    Product(
        sku='STORE-HOODIE',
        category='Hoodies',
        product_name='Hoodie',
        color='',
        size='',
        season='All Season',
        material='Not specified',
        price_zar=750.0,
        stock_quantity=50,
        available_colors=('Black', 'Brown', 'Red'),
        available_sizes=('S', 'M', 'L', 'XL', 'XXL'),
        source='storeInventory',
    ),
    Product(
        sku='STORE-MAFIA-TRACKSUITS',
        category='Tracksuits',
        product_name='Mafia Tracksuits',
        color='',
        size='',
        season='All Season',
        material='Not specified',
        price_zar=1200.0,
        stock_quantity=30,
        available_colors=('Black', 'Navy'),
        available_sizes=('S', 'M', 'L', 'XL', 'XXL'),
        source='storeInventory',
    ),
    Product(
        sku='STORE-SC-WOVEN-TRACKSUITS',
        category='Tracksuits',
        product_name='SC Woven Tracksuits',
        color='',
        size='',
        season='All Season',
        material='Not specified',
        price_zar=1000.0,
        stock_quantity=10,
        available_colors=('Black', 'White'),
        available_sizes=('S', 'M', 'L', 'XL', 'XXL'),
        source='storeInventory',
    ),
    Product(
        sku='STORE-HANDBAG',
        category='Accessories',
        product_name='Handbag',
        color='',
        size='',
        season='All Season',
        material='Not specified',
        price_zar=1000.0,
        stock_quantity=20,
        available_colors=('Black', 'Green'),
        available_sizes=(),
        source='storeInventory',
    ),
    Product(
        sku='STORE-CAP',
        category='Headwear',
        product_name='Cap',
        color='',
        size='',
        season='All Season',
        material='Not specified',
        price_zar=200.0,
        stock_quantity=100,
        available_colors=('Black', 'Brown', 'White', 'Red', 'Blue'),
        available_sizes=(),
        source='storeInventory',
    ),
]
